language: node_js

node_js:
  - "4.2"

before_script:
  - npm install gulp gulp-util gulp-watch gulp-concat gulp-uglify gulp-mocha
  - npm install mocha requirejs should jsdom

script:
    gulp

notifications:
  email:
    - chriclrk@umich.edu